name: app_barber_yha

description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  go_router: ^12.1.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/admin/
    - assets/img/drinkFood/
    - assets/img/products/
    - assets/img/sales/

  fonts:
    - family: Jolly_Lodger
      fonts:
        - asset: assets/fonts/Jolly_Lodger/JollyLodger-Regular.ttf
          style: normal
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
