// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7I9fhiIMctZEeyN8zrQvQ6jrXKTmS1w',
    appId: '1:1064896186069:web:b9f8f80ac4e6b5cc61c45c',
    messagingSenderId: '1064896186069',
    projectId: 'flutter-barber-95bab',
    authDomain: 'flutter-barber-95bab.firebaseapp.com',
    storageBucket: 'flutter-barber-95bab.appspot.com',
    measurementId: 'G-T6DY846RP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3dneB2E0ReDmRpLVxO4HgrY4cMnKPN98',
    appId: '1:1064896186069:android:d4d2dd5864f754c661c45c',
    messagingSenderId: '1064896186069',
    projectId: 'flutter-barber-95bab',
    storageBucket: 'flutter-barber-95bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3eKYq9JNbEGunk_qsub-pSXy4Z1gffrE',
    appId: '1:1064896186069:ios:0e58ae09eb89bbd061c45c',
    messagingSenderId: '1064896186069',
    projectId: 'flutter-barber-95bab',
    storageBucket: 'flutter-barber-95bab.appspot.com',
    iosBundleId: 'com.example.appBarberYha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3eKYq9JNbEGunk_qsub-pSXy4Z1gffrE',
    appId: '1:1064896186069:ios:e6dd184fab19e8fa61c45c',
    messagingSenderId: '1064896186069',
    projectId: 'flutter-barber-95bab',
    storageBucket: 'flutter-barber-95bab.appspot.com',
    iosBundleId: 'com.example.appBarberYha.RunnerTests',
  );
}
